// Nội dung sách. Mỗi khối: [loại, ...dữ liệu]
// Loại: part, lesson, p, steps, bullets, prompt, img, levels, tip, example, why, pb
module.exports = [
['cover'],
['howto'],
['basisTable'],

// ===================== PHẦN A =====================
['part', 'PHẦN A', 'Bắt đầu từ số 0', 'Dành cho thầy cô chưa từng mở một công cụ AI nào. Đọc 3 bài này trước, mất khoảng 20 phút.'],

['lesson', 'A1', 'AI là trợ lý, thầy cô là người quyết định'],
['p', 'Trí tuệ nhân tạo (AI) trong sách này là loại **AI tạo sinh**: thầy cô gõ một câu yêu cầu bằng tiếng Việt, AI viết lại cho mình một đoạn văn, một bảng, một bức ảnh hay một bài hát. Câu yêu cầu đó gọi là **câu lệnh**, tiếng Anh là **prompt**. Cả cuốn sách thực chất chỉ dạy một việc: viết câu lệnh sao cho AI hiểu đúng ý mình.'],
['img', 'h01-vong-lam-viec', 'Hình A1. Vòng làm việc 4 bước với AI: Hỏi, Đọc, Sửa, Kiểm.'],
['why', 'Vì sao phải có bước KIỂM?', 'AI viết rất trôi chảy nên dễ khiến người đọc tin ngay. Nhưng AI có thể "bịa" ra số liệu, tên tác giả hoặc nguồn không có thật. Hiện tượng này thường được gọi là **ảo giác AI**. Vì vậy mọi nội dung đưa cho học sinh đều phải qua mắt thầy cô trước.'],

['lesson', 'A2', 'Mở công cụ và gõ câu lệnh đầu tiên'],
['p', 'Thầy cô chỉ cần một công cụ để bắt đầu. Sách dùng ví dụ trên **ChatGPT** (chatgpt.com) hoặc **Gemini** (gemini.google.com). Cả hai đều có bản miễn phí, dùng được trên điện thoại lẫn máy tính.'],
['steps', [
  'Mở trình duyệt Chrome, gõ **chatgpt.com** hoặc **gemini.google.com** rồi bấm Enter.',
  'Bấm **Đăng nhập**, chọn **Tiếp tục với Google** và chọn tài khoản Gmail của thầy cô.',
  'Nhìn xuống cuối màn hình, tìm ô trống có dòng chữ mờ kiểu "Hỏi bất kỳ điều gì". Đó là **ô nhập câu lệnh**.',
  'Gõ hoặc dán câu lệnh đầu tiên (xem bên dưới), rồi bấm **Enter** hoặc bấm **nút mũi tên**.',
  'Chờ vài giây. Đọc hết câu trả lời. Muốn lấy nội dung, bấm **biểu tượng sao chép** ở cuối câu trả lời rồi dán vào Word.',
]],
['prompt', 'Câu lệnh đầu tiên (sao chép nguyên văn)', ['Cho tôi gợi ý bài giảng về chủ đề quá trình quang hợp.']],
['img', 'h02-khung-chat', 'Hình A2. Sáu vị trí có ở hầu hết công cụ trò chuyện với AI. Tên nút có thể khác đôi chút giữa các công cụ.'],
['bullets', [
  '**Muốn AI sửa:** không cần gõ lại từ đầu. Gõ tiếp ngay bên dưới, ví dụ: "Viết ngắn lại một nửa", "Thêm 1 trò chơi khởi động".',
  '**Làm việc mới:** bấm **Trò chuyện mới** (New chat). Nếu viết chung một cuộc, AI sẽ trộn yêu cầu cũ vào việc mới.',
  '**Xuống dòng trong ô nhập:** giữ **Shift** rồi bấm **Enter**. Chỉ bấm Enter là câu lệnh bị gửi đi luôn.',
]],

['lesson', 'A3', 'Sáu mảnh ghép của một câu lệnh tốt'],
['p', 'Câu lệnh dưới đây là mẫu chuẩn để thầy cô nhìn và bắt chước. Mỗi cụm từ trả lời một câu hỏi mà AI cần biết.'],
['prompt', 'Thành tố của prompt tốt', [
  'Đóng vai trò như một gia sư giỏi, chia nhỏ và giải thích những vấn đề phức tạp một cách dễ hiểu.',
  'Tôi muốn bạn giải thích quá trình quang hợp, cho một học sinh 14 tuổi, để hỗ trợ chuẩn bị cho kỳ thi sinh học. Câu trả lời của bạn nên có 300 từ, được viết bằng giọng điệu thân thiện và giáo dục.',
]],
['img', 'h03-cong-thuc-prompt', 'Hình A3. Tách câu lệnh mẫu thành 6 mảnh ghép.'],
['why', 'Vì sao lại chọn đúng những cụm từ này?', '"**Đóng vai trò như một gia sư giỏi**" cho AI biết nên nói chuyện như người dạy kèm, không như sách giáo khoa. "**Chia nhỏ và giải thích**" nói luôn cách dạy. "**Học sinh 14 tuổi**" quyết định độ khó của từ ngữ. "**Để hỗ trợ chuẩn bị cho kỳ thi**" nhắc AI tập trung vào ý dễ ra đề. "**300 từ**" giới hạn độ dài. "**Thân thiện và giáo dục**" chọn giọng văn. Bỏ bất kỳ cụm nào, AI sẽ tự đoán phần đó.'],
['tip', 'Mẹo ghi nhớ: trước khi bấm gửi, đọc lại câu lệnh và tự hỏi: AI đã biết **Ai nói? Nói cho ai? Để làm gì? Dài bao nhiêu? Giọng thế nào?** chưa.'],

// ===================== PHẦN B =====================
['pb'],
['part', 'PHẦN B', 'Buổi 1 · Kỹ thuật viết câu lệnh', 'Bốn kỹ thuật cơ bản, cách tự chấm câu lệnh và cách nhờ AI soạn bài giảng.'],
['img', 'h04-ky-thuat-prompt', 'Hình B. Bốn kỹ thuật viết câu lệnh, xếp từ đơn giản đến đầy đủ.'],

['lesson', 'B1', 'Kỹ thuật Zero-shot'],
['why', 'Vì sao gọi là "Zero-shot"?', '"Shot" nghĩa là một ví dụ mẫu. "Zero-shot" là hỏi mà **không đưa ví dụ nào**, AI tự làm dựa trên hiểu biết sẵn có. Đây là cách hỏi nhanh nhất, hợp khi thầy cô cần ý tưởng thô.'],
['prompt', 'Câu lệnh gốc', ['Cho tôi gợi ý bài giảng về chủ đề quá trình quang hợp.']],
['example', ['Bài giảng: Quá trình quang hợp', '1. Khởi động: Cho học sinh quan sát hai chậu cây, một chậu để nơi tối...', '2. Hình thành kiến thức: nguyên liệu, điều kiện, sản phẩm của quang hợp...', '3. Luyện tập: sơ đồ điền khuyết...', '4. Vận dụng: Vì sao nên trồng cây xanh trong lớp học?']],
['levels', {
  mn: 'Cho tôi gợi ý một hoạt động khám phá về chủ đề cây xanh cần nước và ánh sáng cho trẻ 5 tuổi.',
  th: 'Cho tôi gợi ý bài giảng về chủ đề thực vật cần gì để sống cho học sinh lớp 4.',
  thcs: 'Cho tôi gợi ý bài giảng về chủ đề quá trình quang hợp cho học sinh lớp 7.',
}],
['tip', 'Kết quả Zero-shot thường chung chung. Đó không phải lỗi của AI mà là do câu lệnh thiếu thông tin. Các kỹ thuật sau sẽ bù vào chỗ thiếu này.'],

['lesson', 'B2', 'Kỹ thuật nhập vai'],
['why', 'Vì sao phải cho AI "nhập vai"?', 'Khi được giao một vai, AI chọn cách nói, cách dùng từ và góc nhìn của vai đó. Mời AI làm **Isaac Newton** thì bài giảng về định luật chuyển động trở thành lời kể ở ngôi thứ nhất, học sinh thấy lạ và nhớ lâu hơn.'],
['prompt', 'Câu lệnh gốc', ['Hãy tưởng tượng bạn là Isaac Newton, hãy tóm tắt lại định luật chuyển động thứ nhất.']],
['levels', {
  mn: 'Hãy tưởng tượng bạn là chú Gà Trống trong trang trại. Hãy kể cho các bé 4 tuổi nghe một ngày của chú bằng 5 câu thật ngắn.',
  th: 'Hãy tưởng tượng bạn là giọt nước. Hãy kể cho học sinh lớp 4 nghe hành trình của bạn trong vòng tuần hoàn của nước.',
  thcs: 'Hãy tưởng tượng bạn là nhà bác học Marie Curie. Hãy kể cho học sinh lớp 8 nghe bạn đã phát hiện ra chất phóng xạ như thế nào.',
}],

['lesson', 'B3', 'Kỹ thuật prompt ĐẢO NGƯỢC (hai cách)'],
['why', 'Vì sao gọi là "đảo ngược"?', 'Bình thường thầy cô hỏi, AI trả lời. Ở kỹ thuật này **vai trò đảo lại**: cách số 1, AI hỏi ngược lại mình những gì nó cần biết. Cách số 2, AI viết câu lệnh giúp mình. Dùng khi thầy cô chưa biết nên viết câu lệnh thế nào cho đủ.'],
['prompt', 'Đảo ngược số 1: để AI hỏi lại mình', ['Bạn cần biết gì để giúp tôi tạo một bài học khoa học xuất sắc cho một lớp học sinh lớp hai?']],
['example', ['Để giúp thầy cô, tôi cần biết:', '1. Chủ đề khoa học cụ thể là gì?', '2. Tiết học kéo dài bao nhiêu phút?', '3. Lớp có bao nhiêu học sinh, có học sinh cần hỗ trợ đặc biệt không?', '4. Lớp có máy chiếu, dụng cụ thí nghiệm gì?', '5. Thầy cô muốn học sinh làm được gì sau tiết học?']],
['steps', [
  'Dán câu lệnh đảo ngược số 1 và gửi.',
  'AI trả về một danh sách câu hỏi. Thầy cô trả lời từng câu ngay trong ô nhập, mỗi ý một dòng.',
  'Gửi câu trả lời. AI sẽ soạn bài học dựa trên đúng thông tin thầy cô vừa cung cấp.',
]],
['prompt', 'Đảo ngược số 2: để AI viết câu lệnh tạo ảnh', ['Giúp tôi viết prompt để tạo ảnh theo phong cách tương tự của ảnh đính kèm']],
['steps', [
  'Bấm dấu **+** (hoặc biểu tượng kẹp giấy) trong ô nhập, chọn một bức ảnh thầy cô thích.',
  'Dán câu lệnh trên và gửi. AI sẽ mô tả phong cách ảnh thành một câu lệnh hoàn chỉnh.',
  'Sao chép câu lệnh đó, thay nội dung bằng chủ đề bài học của mình, rồi dùng để tạo ảnh mới.',
]],

['lesson', 'B4', 'Kỹ thuật kết hợp nhiều yếu tố'],
['why', 'Vì sao lại là "kết hợp"?', 'Câu lệnh này gộp cùng lúc **vai** (nhà thám hiểm), **đối tượng** (học sinh lớp 6), **nội dung hoạt động** (lời dẫn, mô tả, câu hỏi, gợi ý đáp án) và **khung trình bày** (5 mục). Khi có khung, AI trả về đúng thứ tự thầy cô cần, dán thẳng vào giáo án được.'],
['prompt', 'Câu lệnh gốc', [
  'Bạn là một nhà thám hiểm. Hãy viết đoạn dẫn nhập cho bài học về "Các đới khí hậu trên Trái Đất" cho học sinh lớp 6.',
  'Hoạt động cần có lời dẫn, mô tả cảnh quan, câu hỏi và gợi ý đáp án. Hãy bổ sung một prompt để AI vẽ lại cảnh quan được mô tả.',
  'Trình bày theo cấu trúc:',
  'Giới thiệu chuyến đi',
  'Trạm dừng số 1',
  'Câu hỏi khám phá',
  'Chốt kiến thức',
  'Gợi ý ảnh minh họa (Prompt cho AI vẽ)',
]],
['p', 'Điểm hay của câu lệnh: dòng "**Hãy bổ sung một prompt để AI vẽ lại cảnh quan**" khiến AI tự viết luôn câu lệnh vẽ ảnh. Thầy cô chỉ việc sao chép dòng đó sang một cuộc trò chuyện mới để có ảnh minh họa cho slide.'],
['levels', {
  mn: 'Bạn là cô Tiên xanh. Hãy viết lời dẫn cho hoạt động khám phá "Các mùa trong năm" cho trẻ 5 tuổi. Trình bày theo cấu trúc: Lời chào, Chuyến thăm mùa hè, Câu hỏi cho bé, Chốt lại, Prompt cho AI vẽ.',
  th: 'Bạn là một hướng dẫn viên du lịch. Hãy viết đoạn dẫn nhập cho bài "Thiên nhiên vùng Nam Bộ" cho học sinh lớp 4. Trình bày theo cấu trúc: Giới thiệu chuyến đi, Trạm dừng số 1, Câu hỏi khám phá, Chốt kiến thức, Gợi ý ảnh minh họa (Prompt cho AI vẽ).',
  thcs: 'Dùng nguyên câu lệnh gốc cho lớp 6. Với lớp 8, 9 đổi chủ đề thành bài đang dạy.',
}],

['lesson', 'B5', 'Đánh giá prompt và cải thiện prompt'],
['p', 'Cách tự chấm một câu lệnh: đối chiếu với 6 mảnh ghép ở bài A3. Thiếu mảnh nào thì thêm mảnh đó.'],
['prompt', 'Prompt cần đánh giá', ['Tìm cho tôi 3 nguyên nhân chính gây ra ô nhiễm không khí ở các thành phố lớn để sử dụng trong bài thuyết trình.']],
['prompt', 'Prompt cải thiện', ['Hãy nhập vai một giáo viên môn Địa lý, nhiệt tình và dễ hiểu. Giúp tôi liệt kê 3 nguyên nhân chính gây ra ô nhiễm không khí ở các thành phố lớn, kèm theo mỗi nguyên nhân là một mô tả ngắn từ 2-3 câu. Nội dung sẽ được tôi sử dụng cho bài thuyết trình trong lớp học, vì vậy hãy trình bày ngắn gọn, rõ ràng và dễ nhớ cho học sinh cấp 3.']],
['img', 'h05-truoc-sau', 'Hình B5. Những cụm từ được thêm vào (tô vàng) chính là các mảnh ghép còn thiếu.'],
['tip', 'Thầy cô THCS chỉ cần đổi "học sinh cấp 3" thành "học sinh lớp 8". Thầy cô tiểu học đổi thành "học sinh lớp 5" và "mỗi nguyên nhân 1 câu".'],

['lesson', 'B6', 'Nhờ AI soạn bài giảng và tìm học liệu'],
['prompt', 'Câu lệnh soạn bài giảng 10 slide', ['Bạn là giáo viên tiểu học và đang soạn một bài giảng môn Địa lý cho HS lớp 4 về chủ đề "Thiên nhiên vùng Nam Bộ". Bài giảng gồm 10 slide, trong đó bao gồm: mục tiêu bài học, nội dung kiến thức, 5 câu hỏi Quiz củng cố bài (có đáp án kèm theo). Trong đó cần có 1 hoạt động nhóm 7 phút tìm hiểu về cách bảo vệ tài nguyên thiên nhiên vùng Nam Bộ.']],
['p', 'Câu lệnh này nêu rõ **số slide**, **thành phần bắt buộc** và **thời lượng hoạt động nhóm**. Nhờ con số cụ thể, AI không thể trả lời lan man.'],
['prompt', 'Câu lệnh tìm học liệu đa dạng', ['Tôi là giáo viên và đang xây dựng một khóa học online trên Teams về Hệ mặt trời dành cho học sinh lớp 4. Hãy giúp tôi tìm các loại học liệu đa dạng để cung cấp kiến thức cho học sinh, bao gồm video, bài đọc, website, bài hát và truyện tranh.']],
['tip', 'Đường link video, website do AI gợi ý có thể đã hỏng hoặc không tồn tại. Bấm mở từng link trước khi gửi cho học sinh.'],

['lesson', 'B7', 'Mô hình TPACK'],
['why', 'TPACK là gì?', 'TPACK là viết tắt tiếng Anh của **Kiến thức Công nghệ, Sư phạm và Nội dung**. Người dạy giỏi với công nghệ phải trả lời cùng lúc 3 câu: **dạy cái gì (CK)**, **dạy bằng cách nào (PK)**, **dùng công cụ gì (TK)**. Câu lệnh TPACK viết đủ 3 dòng này để AI đề xuất ý tưởng nằm ở chỗ giao nhau.'],
['img', 'h06-tpack', 'Hình B7. Ba vòng tròn CK, PK, TK và vùng giao nhau TPACK.'],
['prompt', 'Câu lệnh TPACK (Khoa học lớp 4)', [
  'Bạn là một giáo viên giỏi với nhiều năm kinh nghiệm, hãy giúp tôi đề xuất các ý tưởng theo mô hình TPACK để dạy bài Vòng tuần hoàn của nước, trong chương trình môn Khoa học cho học sinh lớp 4 theo các kiến thức sau đây:',
  '- Kiến Thức Nội Dung (CK): Chủ đề vòng tuần hoàn của nước trong tự nhiên',
  '- Kiến Thức Sư Phạm (PK): dạy học dự án, khuyến khích học sinh khám phá chủ đề, hiểu và có khả năng tự vẽ được vòng tuần hoàn của nước trong tự nhiên.',
  '- Kiến Thức Công Nghệ (TK): Công cụ Generative AI hỗ trợ trình bày sản phẩm',
]],
['prompt', 'Prompt chi tiết (Ngữ văn lớp 8). Phần trong [ ] là chỗ thầy cô thay', [
  'Bạn là một giáo viên giỏi với nhiều năm kinh nghiệm, hãy giúp tôi đề xuất các ý tưởng theo mô hình TPACK để dạy bài ["Lão Hạc" của Nam Cao] cho [học sinh lớp 8] theo các kiến thức sau đây:',
  '- Kiến Thức Nội Dung (CK): Chủ đề: Phân tích tác phẩm "Lão Hạc" của Nam Cao',
  '- Kiến Thức Sư Phạm (PK): Chiến lược giảng dạy là khuyến khích học sinh khám phá chủ đề, phát triển nhân vật và ngôn ngữ qua thảo luận và dự án sáng tạo.',
  '- Kiến Thức Công Nghệ (TK): Công cụ: Generative AI hỗ trợ viết sáng tạo và trình bày sản phẩm.',
]],
['tip', 'Dấu ngoặc vuông [ ] trong câu lệnh mẫu nghĩa là "điền vào đây". Khi dùng, thầy cô xóa cả dấu ngoặc và thay bằng nội dung của mình.'],

// ===================== PHẦN C =====================
['pb'],
['part', 'PHẦN C', 'Buổi 2 · Kế hoạch bài dạy và kiểm tra đánh giá', 'Từ giáo án tích cực, đề tự luận, đề trắc nghiệm theo ma trận đến bảng tiêu chí chấm điểm.'],

['lesson', 'C1', 'Kế hoạch bài dạy theo kỹ thuật dạy học tích cực'],
['why', 'Kỹ thuật góc trạm là gì?', 'Lớp học được chia thành nhiều "trạm" (góc), mỗi trạm là một nhiệm vụ nhỏ. Các nhóm học sinh **luân phiên di chuyển** qua từng trạm để làm thí nghiệm, đọc tài liệu, giải bài tập. Viết hoa "**KỸ THUẬT GÓC TRẠM**" trong câu lệnh là để AI không bỏ sót yêu cầu quan trọng nhất.'],
['prompt', 'Câu lệnh gốc', ['Thiết kế một giáo án bài học 90 phút theo chủ đề xoay quanh chủ đề \'Khám phá Hệ sinh thái\'. Nhóm học sinh mục tiêu của bạn là lớp 5. Cách tiếp cận nên nhấn mạnh vào việc khám phá thực hành, học tập hợp tác và có ứng dụng KỸ THUẬT GÓC TRẠM']],
['levels', {
  mn: 'Thiết kế một hoạt động 30 phút chủ đề "Các con vật nuôi trong gia đình" cho trẻ 4-5 tuổi, tổ chức theo 4 góc chơi: góc xây dựng, góc nghệ thuật, góc sách, góc phân vai.',
  th: 'Dùng nguyên câu lệnh gốc cho lớp 5. Có thể đổi thời lượng thành 70 phút (2 tiết).',
  thcs: 'Thiết kế một kế hoạch bài dạy 90 phút chủ đề "Hệ sinh thái" môn Khoa học tự nhiên lớp 8, có ứng dụng KỸ THUẬT GÓC TRẠM với 4 trạm.',
}],

['lesson', 'C2', 'Kế hoạch bài dạy STEM, STEAM'],
['why', 'Hiểu đúng các cụm từ', '**DIY** (Do It Yourself) nghĩa là học sinh tự tay làm. **Quy trình Thiết kế Kỹ thuật** (Engineering Design Process) là chuỗi bước: xác định vấn đề, tìm hiểu, đề xuất ý tưởng, làm mẫu thử, thử nghiệm, cải tiến, chia sẻ. Ghi tên quy trình vào câu lệnh thì AI sẽ chia giáo án theo đúng các bước này.'],
['prompt', 'Câu lệnh gốc', ['Thiết kế một giáo án bài dạy DIY STEM về chủ đề nam châm điện ở trường phổ thông, sử dụng Quy trình Thiết Kế Kỹ Thuật (Engineering Design Process)']],
['levels', {
  mn: 'Thiết kế một hoạt động STEAM 30 phút cho trẻ 5 tuổi: làm chiếc thuyền nổi từ vật liệu tái chế, chia thành các bước quan sát, dự đoán, làm thử, thử trên chậu nước, kể lại.',
  th: 'Thiết kế một giáo án bài dạy DIY STEM cho học sinh lớp 5 về chủ đề làm đèn pin đơn giản, sử dụng Quy trình Thiết Kế Kỹ Thuật (Engineering Design Process)',
  thcs: 'Dùng nguyên câu lệnh gốc, thêm "cho học sinh lớp 9, thời lượng 2 tiết".',
}],

['lesson', 'C3', 'Đề kiểm tra tự luận (cách cơ bản)'],
['p', 'Câu lệnh này đáng học vì nó **tách riêng từng đề** và gắn mỗi đề với một **mức độ** cụ thể (Thông hiểu, Vận dụng, Vận dụng cao). Nhờ vậy đề không bị cùng một độ khó.'],
['prompt', 'Câu lệnh gốc (Ngữ văn 12)', [
  'Hãy đóng vai một giáo viên Ngữ văn giàu kinh nghiệm tại Việt Nam. Soạn thảo 03 đề thi tự luận cho học sinh lớp 12, bám sát Chương trình GDPT 2018. Các đề thi cần tập trung vào văn bản "Tây Tiến" của nhà thơ Quang Dũng.',
  'Yêu cầu chi tiết:',
  'Đề 1 (Mức độ Thông hiểu - Phân tích): Yêu cầu học sinh phân tích một đoạn thơ cụ thể trong bài thơ, làm nổi bật vẻ đẹp bi tráng của hình tượng người lính Tây Tiến.',
  'Đề 2 (Mức độ Vận dụng - So sánh): Yêu cầu học sinh so sánh hình tượng người lính trong bài thơ "Tây Tiến" với hình tượng người lính trong bài thơ "Đồng chí" của Chính Hữu để làm rõ những điểm tương đồng và khác biệt trong cảm hứng của hai nhà thơ.',
  'Đề 3 (Mức độ Vận dụng cao - Nghị luận và Liên hệ): Từ hình tượng người lính Tây Tiến, yêu cầu học sinh trình bày suy nghĩ về lý tưởng sống của thế hệ trẻ ngày nay.',
  'Mỗi đề cần có gợi ý về cấu trúc và những ý chính cần đạt được.',
]],
['levels', {
  mn: 'Không áp dụng đề thi. Có thể đổi thành: "Soạn 3 câu hỏi trò chuyện với trẻ 5 tuổi sau khi nghe truyện Tấm Cám, từ dễ đến khó".',
  th: 'Giữ khung câu lệnh. Đổi thành "học sinh lớp 5", văn bản "Chiếc rễ đa tròn" và 3 đề viết đoạn văn ngắn.',
  thcs: 'Giữ khung câu lệnh. Đổi thành "học sinh lớp 9", văn bản "Đồng chí" của Chính Hữu.',
}],

['lesson', 'C4', 'Đề trắc nghiệm có đính kèm tài liệu'],
['prompt', 'Câu lệnh gốc (Tiếng Anh tiểu học)', [
  'Tôi là giáo viên tiếng Anh tiểu học, đang dạy theo sách Family and Friends 4 - Class Book. Hãy giúp tôi tạo một bài kiểm tra trắc nghiệm gồm 5 câu hỏi để ôn tập bài Unit 2 - "The Concert".',
  'Các câu hỏi cần có mức độ đa dạng (dễ - trung bình - khó), mỗi câu có 4 lựa chọn A, B, C, D và chỉ có 1 đáp án đúng.',
  'Tài liệu đính kèm: Sách Family and Friends 4 - Class Book',
]],
['steps', [
  'Tải tệp sách về máy (link ở Phụ lục).',
  'Trong ô nhập, bấm dấu **+**, chọn **Tải tệp lên**, chọn tệp PDF vừa tải.',
  'Chờ thanh tải chạy xong, dán câu lệnh, bấm gửi.',
  'Kiểm tra từng câu: đáp án đúng có nằm trong bài Unit 2 không, có câu nào hai đáp án cùng đúng không.',
]],
['tip', 'Câu "**chỉ có 1 đáp án đúng**" rất quan trọng. Thiếu câu này, AI đôi khi viết câu hỏi có hai đáp án cùng hợp lý.'],

['lesson', 'C5', 'Câu lệnh nâng cao: chia 4 ngăn có tiêu đề #'],
['why', 'Vì sao lại dùng dấu #?', 'Khi câu lệnh dài và có nhiều tài liệu, AI dễ lẫn đâu là yêu cầu, đâu là dữ liệu. Dấu **#** tạo tiêu đề lớn, dấu **##** đặt tên cho từng tài liệu. Trong câu lệnh, câu "**Đọc nội dung bài học ở mục ##Nội dung bài học**" chỉ đúng tệp cần đọc.'],
['img', 'h07-cau-truc-4-muc', 'Hình C5. Bốn ngăn của một câu lệnh nâng cao.'],
['prompt', 'Câu lệnh gốc: bộ câu hỏi Hóa học 10', [
  '#NGỮ CẢNH',
  'Bạn là một giáo viên Hóa học có chuyên môn vững chắc, nhiều năm kinh nghiệm giảng dạy. Bạn đang giảng dạy môn Hóa học 10 - Bộ sách Cánh diều. Nội dung giảng dạy là cấu tạo nguyên tử',
  '#HƯỚNG DẪN',
  'Đọc nội dung bài học ở mục ##Nội dung bài học',
  'Dựa vào nội dung đã đọc, tạo 10 câu hỏi trắc nghiệm 4 đáp án',
  'Dựa vào mục ##Mức độ nhận thức để xác định được thế nào là câu hỏi nhận biết, thông hiểu và vận dụng',
  '#DỮ LIỆU',
  '##Nội dung bài học: Tài liệu đính kèm có tên: Hóa học 10 - Bài 2. Thành phần của nguyên tử.pdf',
  '##Mức độ nhận thức: Tài liệu đính kèm có tên: Hóa học - Mô tả mức độ nhận thức',
  '#YÊU CẦU',
  '10 câu hỏi trắc nghiệm lựa chọn 4 đáp án, trong đó có 5 câu hỏi nhận biết, 3 câu hỏi thông hiểu, 2 câu hỏi vận dụng',
  'Chỉ sử dụng nội dung trong tài liệu đính kèm, có thể thay đổi ví dụ',
  'Không sử dụng nội dung của file trong mục ##Mức độ nhận thức để tạo câu hỏi',
  'Câu hỏi được trình bày trong file .docx',
]],
['p', 'Dòng "**Không sử dụng nội dung của file trong mục ##Mức độ nhận thức để tạo câu hỏi**" chặn một lỗi hay gặp: AI lấy luôn câu chữ trong tệp mô tả mức độ để ra đề. Tệp đó chỉ để AI hiểu cách phân loại câu hỏi.'],
['levels', {
  mn: 'Không áp dụng.',
  th: 'Giữ 4 ngăn. #NGỮ CẢNH: giáo viên Toán lớp 3 bộ sách của trường. #DỮ LIỆU: đính kèm bài học. #YÊU CẦU: 6 câu, 3 nhận biết, 2 thông hiểu, 1 vận dụng.',
  thcs: 'Giữ nguyên khung, đổi thành môn và bộ sách đang dạy, ví dụ Khoa học tự nhiên 7.',
}],

['lesson', 'C6', 'Đề thi theo ma trận và bản đặc tả'],
['why', 'Hiểu đúng các cụm từ', '**Ma trận đề** là bảng thiết kế đề: mỗi nội dung có bao nhiêu câu ở mỗi mức độ. **Bản đặc tả** mô tả cụ thể học sinh phải làm được gì ở từng mức. Có đủ hai tệp này, AI ra đề sát cấu trúc nhà trường yêu cầu.'],
['img', 'h08-muc-do-nhan-thuc', 'Hình C6. Bốn mức độ nhận thức, dùng nguyên văn định nghĩa để dán vào câu lệnh.'],
['prompt', 'Câu lệnh gốc: đề Tin học 6 (40 câu)', [
  '#NGỮ CẢNH',
  'Bạn là một giáo viên môn Tin học có chuyên môn vững chắc, nhiều năm kinh nghiệm giảng dạy. Bạn đang giảng dạy môn Tin học lớp 6 - Bộ sách Cánh diều.',
  '#HƯỚNG DẪN',
  'Đọc các tài liệu ở mục ##Ma trận đề kiểm tra, ##Bảng đặc tả, ##Nội dung dạy học',
  'Dựa vào nội dung đã đọc, tạo một đề thi với 40 câu hỏi trắc nghiệm lựa chọn 4 đáp án.',
  'Dựa vào bảng hỏi của từng nội dung ở cột (3) đúng với các mức độ nhận thức: Nhận biết (cột 5), Thông hiểu (cột 6), Vận dụng (cột 7) và Vận dụng cao (cột 8) được mô tả trong tài liệu ở mục ##Ma trận đề kiểm tra.',
  'Dựa vào mục ##Mức độ nhận thức để biết thế nào là câu hỏi Nhận biết, Thông hiểu và Vận dụng.',
  '#DỮ LIỆU',
  '##Ma trận đề kiểm tra: Tài liệu đính kèm có tên: Tin học 6 - Ma trận đề kiểm tra - GHKI.docx',
  '##Bảng đặc tả: Tài liệu đính kèm có tên: Tin học 6 - Bảng mô tả mức độ đánh giá - A và B.docx',
  '##Nội dung dạy học: Tài liệu đính kèm có tên: Tin học 6 - Chủ đề A và B.pdf',
  '##Mức độ nhận thức: Tài liệu đính kèm có tên: Tin học 6 - Mức độ nhận thức.docx',
  '#YÊU CẦU',
  'Đưa ra đề thi gồm 40 CÂU HỎI TRẮC NGHIỆM LỰA CHỌN 4 ĐÁP ÁN chia thành 2 phần trả lời',
  'Mỗi câu hỏi có mức độ nhận thức Nhận biết, Thông hiểu, Vận dụng và Vận dụng cao',
  'Câu hỏi được xây dựng theo ma trận đề ##Nội dung dạy học và mức độ nhận thức',
]],
['tip', 'Tên nhãn ## ở phần #HƯỚNG DẪN phải **viết giống hệt** tên nhãn ở phần #DỮ LIỆU. Viết "##Bản đặc tả" ở chỗ này và "##Bảng đặc tả" ở chỗ kia là AI có thể không nhận ra đó là cùng một tệp.'],
['tip', 'Đề 40 câu dài. Nếu AI dừng giữa chừng, gõ "**Viết tiếp từ câu 21**".'],

['lesson', 'C7', 'Xây dựng tiêu chí đánh giá (rubric)'],
['why', 'Rubric là gì?', 'Rubric là **bảng tiêu chí chấm điểm**: mỗi hàng là một tiêu chí, mỗi cột là một mức. Học sinh nhìn bảng biết mình cần làm gì để đạt điểm cao. Giáo viên chấm nhanh, công bằng hơn.'],
['prompt', 'Câu lệnh gốc: chấm trò chơi Scratch', [
  '#NGỮ CẢNH',
  'Bạn là một giáo viên Tin học có chuyên môn vững chắc, nhiều năm kinh nghiệm giảng dạy. Bạn đang cho học sinh thực hiện thiết kế trò chơi trên Scratch để ôn tập các kiến thức đã học của môn học khác.',
  '#HƯỚNG DẪN',
  'Bạn cần xây dựng bảng tiêu chí đánh giá sản phẩm trò chơi của học sinh. Các tiêu chí phải đảm bảo đánh giá được cả nội dung kiến thức, khả năng lập trình và yếu tố sáng tạo trong sản phẩm.',
  'Mỗi tiêu chí cần được mô tả rõ ràng, với 4 mức đánh giá: Rất tốt (4 điểm), Tốt (3 điểm), Trung bình (2 điểm), Chưa đạt yêu cầu (1 điểm)',
  '#YÊU CẦU',
  'Trình bày tiêu chí đánh giá theo dạng bảng.',
  'Ngôn ngữ rõ ràng, dễ hiểu, phù hợp cho cả học sinh và giáo viên sử dụng khi nhận xét/chấm điểm sản phẩm.',
  'Số lượng tiêu chí từ 4 đến 6 tiêu chí, bao quát các khía cạnh: kiến thức môn học, kỹ năng lập trình, giao diện/sự tương tác, tính sáng tạo và mức độ hoàn thiện của trò chơi.',
]],
['img', 'h09-rubric', 'Hình C7. Khung bảng tiêu chí 4 mức mà AI sẽ điền nội dung.'],
['levels', {
  mn: 'Đổi thành bảng quan sát 3 mức (Thường xuyên, Đôi khi, Chưa thấy) cho hoạt động xếp hình của trẻ 5 tuổi, dùng từ ngữ để giáo viên ghi nhận xét.',
  th: 'Đổi sản phẩm thành "tranh vẽ poster bảo vệ môi trường lớp 3", 4 tiêu chí, ngôn ngữ học sinh lớp 3 đọc hiểu được.',
  thcs: 'Dùng nguyên câu lệnh gốc.',
}],

['lesson', 'C8', 'Đề kiểm tra có công thức toán: xuất sang Overleaf'],
['why', 'LaTeX và Overleaf là gì?', '**LaTeX** là cách gõ văn bản bằng mã, chuyên dùng cho công thức toán đẹp. **Overleaf** (overleaf.com) là trang web miễn phí để dán mã LaTeX và xuất ra PDF. Dòng "\\usepackage[vietnamese]{babel}" giúp hiển thị đúng dấu tiếng Việt.'],
['prompt', 'Câu lệnh gốc', [
  'Bạn là một giáo viên toán phổ thông với nhiều năm kinh nghiệm, hãy tạo cho tôi một đề kiểm tra học kỳ 1 môn toán lớp 12 bộ sách kết nối tri thức với cuộc sống gồm 10 câu trắc nghiệm trong đó có 2 câu nhận biết, 3 câu thông hiểu, 3 câu vận dụng và 2 câu vận dụng cao.',
  'Trình bày bằng latex, sử dụng cho overleaf, lưu ý sử dụng \\usepackage[vietnamese]{babel} để hỗ trợ tiếng Việt',
]],
['steps', [
  'Gửi câu lệnh. AI trả về một khung mã bắt đầu bằng \\documentclass.',
  'Bấm **Sao chép mã** ở góc khung mã.',
  'Vào **overleaf.com**, đăng nhập bằng Google, bấm **New Project**, chọn **Blank Project**, đặt tên.',
  'Xóa hết nội dung mẫu, dán mã vừa sao chép, bấm **Recompile**. Bản PDF hiện ở bên phải, bấm biểu tượng tải về.',
]],
['tip', 'Giáo viên THCS đổi "lớp 12" thành lớp mình dạy. Nếu Overleaf báo lỗi đỏ, sao chép dòng lỗi dán lại cho AI kèm câu "Sửa lỗi này giúp tôi".'],

['lesson', 'C9', 'Tìm kiếm và phân tích thông tin'],
['prompt', 'Câu lệnh tìm kiếm thông tin', ['Tóm tắt 2 tác động của biến đổi khí hậu tại Việt Nam, mỗi tác động kèm ví dụ thực tế, số liệu và nguồn tham khảo (trang báo chính thống, tổ chức như UNDP, World Bank, hoặc các báo Việt Nam). Viết đơn giản để học sinh cấp 3 hiểu.']],
['prompt', 'Câu lệnh phân tích thông tin (hỏi tiếp)', ['Các nguồn thông tin trên đề xuất những giải pháp nào để chống biến đổi khí hậu? Hãy so sánh các giải pháp đó và trình bày chúng dưới dạng bảng tổng hợp.']],
['p', 'Câu lệnh thứ hai dùng cụm "**các nguồn thông tin trên**": AI chỉ phân tích lại những nguồn vừa tìm, không đi lan man. Công cụ hợp nhất cho việc này là **NotebookLM** (notebooklm.google.com): thầy cô tải tài liệu lên, AI chỉ trả lời dựa trên tài liệu đó và ghi chú đoạn nào lấy từ đâu.'],
['steps', [
  'Vào **notebooklm.google.com**, đăng nhập Gmail, bấm **Tạo mới**.',
  'Thêm nguồn: tải PDF, dán link trang web hoặc link YouTube.',
  'Gõ câu lệnh phân tích ở ô chat. Bấm vào các số nhỏ trong câu trả lời để xem đoạn gốc.',
]],

// ===================== PHẦN D =====================
['pb'],
['part', 'PHẦN D', 'Buổi 3 · Sản phẩm đa phương tiện', 'Ảnh, trò chơi, truyện tranh, bài hát, giọng đọc, hội thoại: những thứ trước đây phải thuê người làm.'],
['img', 'h11-ban-do-cong-cu', 'Hình D. Chọn công cụ theo sản phẩm muốn làm.'],

['lesson', 'D1', 'Tạo ảnh với các phong cách'],
['prompt', 'Câu lệnh gốc: đổi phần [...] thành tên phong cách', ['Tạo hình ảnh minh họa cho câu chuyện Hai Bà Trưng cưỡi voi theo phong cách [...]']],
['p', 'Lần lượt thay [...] bằng **Pixar**, **Anime**, **Ghibli Studio** để thấy cùng một nội dung được vẽ theo 3 kiểu khác nhau.'],
['img', 'h10-tao-anh', 'Hình D1. Công thức: Nội dung + Phong cách.'],
['prompt', 'Câu lệnh tạo ảnh thực hành', ['Tạo hình ảnh miêu tả cô bé quàng khăn đỏ đang mang bánh cho bà trong truyện Cô bé quàng khăn đỏ']],
['levels', {
  mn: 'Tạo hình ảnh chú thỏ trắng đang tưới cây trong vườn rau theo phong cách tranh màu nước, màu sắc tươi sáng, nét vẽ đơn giản cho trẻ mầm non.',
  th: 'Tạo hình ảnh minh họa cho câu chuyện Thánh Gióng bay về trời theo phong cách Pixar, khổ ngang 16:9.',
  thcs: 'Tạo hình ảnh minh họa cảnh "Ao thu lạnh lẽo nước trong veo" trong bài Thu điếu theo phong cách tranh thủy mặc.',
}],
['tip', 'Ảnh có chữ tiếng Việt thường bị sai dấu. Nên yêu cầu "**không có chữ trong ảnh**", sau đó tự gõ chữ bằng PowerPoint hoặc Canva.'],

['lesson', 'D2', 'Biến nét vẽ thành ảnh chân thật và prompt đảo ngược cho ảnh'],
['prompt', 'Prompt biến nét vẽ thành ảnh chân thật', ['Hãy chuyển phác thảo này thành một ảnh chân thật. Các chữ nếu có trong phác thảo chỉ là hướng dẫn chi tiết, không nên xuất hiện trong ảnh kết quả. Có thể bổ sung thông tin về phong cách, ví dụ "ảnh 3D hoạt hình Pixar"']],
['steps', [
  'Vẽ tay trên giấy (hoặc để học sinh vẽ), ghi chú bằng chữ các chi tiết như "cây bàng", "cổng trường".',
  'Chụp ảnh bằng điện thoại, đính kèm vào ô nhập bằng dấu **+**.',
  'Dán câu lệnh trên. Câu "các chữ... không nên xuất hiện" giúp AI hiểu chữ chỉ là ghi chú.',
]],
['prompt', 'Prompt đảo ngược cho ảnh', ['Giúp tôi viết một prompt để tạo ra thứ gì đó giống như thế này']],
['p', 'Đính kèm một ảnh mẫu (ví dụ sơ đồ lọc nước). AI trả về câu lệnh mô tả ảnh. Tiếp theo gõ: "**Chỉnh sửa thông tin để phù hợp với xử lý nước**", rồi "**Tạo hình ảnh**". Thầy cô được một ảnh cùng phong cách nhưng đúng nội dung bài mình.'],
['tip', 'Ảnh AI bị lỗi nhỏ (thừa ngón tay, chữ sai dấu)? Mở ảnh trong **Canva** (canva.com/vi_vn/giao-duc), dùng công cụ tẩy hoặc chỉnh sửa bằng AI của Canva để sửa riêng vùng lỗi.'],

['lesson', 'D3', 'Tạo trò chơi, mô phỏng học tập'],
['why', 'Trò chơi được tạo ra bằng cách nào?', 'Thầy cô chỉ mô tả luật chơi bằng lời. AI tự viết mã lập trình rồi hiện ra trò chơi bấm được ngay. Trên **Canva**, tính năng này nằm ở mục Canva AI, chọn kiểu **Code** (Viết code cho tôi). Trên **Gemini**, chọn công cụ **Canvas** trong ô nhập.'],
['prompt', 'Câu lệnh gốc trên Canva (mầm non)', ['Tạo một mô phỏng học tập giúp trẻ mầm non nhận biết các hình học cơ bản như hình tròn, vuông, tam giác. Trẻ có thể kéo thả các hình vào đúng vị trí trên một bức tranh. Mỗi lần hoàn thành chính xác sẽ có phần thưởng hình ảnh động hoặc tiếng vỗ tay. Giao diện nên có màu sắc tươi sáng và thao tác đơn giản']],
['prompt', 'Câu lệnh gốc trên Gemini (Vật lý)', ['Tạo một trò chơi mô phỏng vật lý nơi người chơi điều chỉnh lực và góc bắn để đưa pháo bắn trúng mục tiêu. Trò chơi minh họa định luật 2 Newton (F = ma) và quỹ đạo chuyển động của vật trong không khí. Giao diện nên có đồ họa hoạt hình đơn giản, hiệu ứng chuyển động thực tế và biểu đồ lực - gia tốc minh họa trực quan']],
['p', 'Mỗi câu lệnh game tốt có 4 phần: **mục tiêu học tập** (nhận biết hình học), **cách chơi** (kéo thả), **phần thưởng** (vỗ tay), **giao diện** (tươi sáng, đơn giản). Thiếu cách chơi, AI sẽ tự nghĩ ra luật có thể không hợp với lớp mình.'],
['levels', {
  mn: 'Dùng nguyên câu lệnh Canva. Có thể đổi hình học thành "màu sắc" hoặc "con vật và tiếng kêu".',
  th: 'Tạo trò chơi ôn bảng nhân 7 cho học sinh lớp 2: 10 câu hỏi, 3 đáp án, trả lời đúng có tiếng vỗ tay, cuối game hiện số sao đạt được.',
  thcs: 'Tạo mô phỏng mạch điện nối tiếp và song song cho học sinh lớp 9, học sinh kéo bóng đèn và công tắc vào mạch, bóng sáng khi mạch kín.',
}],
['tip', 'Trò chơi hiện ra nhưng có lỗi? Gõ tiếp mô tả lỗi bằng lời thường, ví dụ: "Kéo hình tròn vào ô vuông vẫn được tính đúng, hãy sửa". Không cần biết lập trình.'],

['lesson', 'D4', 'Truyện tranh nhiều cảnh'],
['prompt', 'Câu lệnh gốc (Google AI Studio hoặc ChatGPT)', ['Viết cho tôi một câu chuyện về một cậu bé nhặt được của rơi và cách cậu xử lý tình huống đó. Tạo hình ảnh minh họa cho từng cảnh theo phong cách hoạt hình 3D, màu sắc tươi sáng, phù hợp với học sinh tiểu học. Câu chuyện có thể chia thành 4 cảnh, thể hiện rõ diễn biến từ lúc nhặt được đồ cho đến khi đưa trả hoặc tìm lại người mất. Nhân vật và bối cảnh cần được giữ đồng bộ, nhất quán xuyên suốt toàn bộ truyện. Kích thước hình ảnh 16:9, không cần lời thoại trong hình.']],
['why', 'Vì sao phải viết "giữ đồng bộ, nhất quán"?', 'Mỗi lần vẽ, AI dễ đổi áo, đổi kiểu tóc nhân vật. Câu này nhắc AI giữ nguyên một nhân vật qua 4 cảnh. "**Không cần lời thoại trong hình**" tránh lỗi chữ tiếng Việt bị sai dấu trong ảnh.'],
['prompt', 'Truyện có nhiều nhân vật: gán mã số cho nhân vật', ['Gán và lưu mã số bất kỳ cho nhân vật này. Tôi sẽ tham chiếu và tạo ảnh sau đó']],
['p', 'Sau khi có ảnh nhân vật ưng ý, dán câu trên. AI trả về một mã, ví dụ "NV01". Những lần sau chỉ cần viết "**Vẽ NV01 đang chào cô giáo ở cổng trường**" là nhân vật giữ nguyên dáng vẻ.'],

['lesson', 'D5', 'Sáng tác bài hát cho trẻ'],
['why', 'Vì sao câu lệnh có một đoạn tiếng Anh?', 'Công cụ tạo nhạc như **Suno** (suno.com) có 2 ô: ô **Lời bài hát** (Lyrics) và ô **Phong cách** (Style of Music). Ô phong cách hiểu tiếng Anh tốt hơn. **BPM** là số nhịp mỗi phút: 110-130 là nhịp nhanh, vui, hợp cho trẻ nhún nhảy.'],
['prompt', 'Câu lệnh gốc: dán vào ChatGPT hoặc Gemini để viết lời', [
  'Tạo một bài hát vui tươi, rộn ràng, phù hợp với trẻ mẫu giáo',
  'Cấu trúc bài hát: Gồm 4 đoạn:',
  'a. 3 khổ đầu, mỗi khổ nói về một loài động vật sống trong rừng (ví dụ: khỉ, voi, chim cú)',
  '- Mỗi khổ bắt đầu bằng việc lặp lại tên loài vật đó 3 lần',
  '- Sau đó là một câu ngắn, vui nhộn, có vần điệu, miêu tả hành động hoặc đặc điểm dễ thương của loài vật',
  '- Ưu tiên vần rõ ràng, dễ nhớ, dễ hát theo cho trẻ nhỏ',
  '- Lặp lại và nhịp điệu là yếu tố quan trọng',
  'b. Đoạn kết tổng hợp lại hình ảnh các con vật, tạo không khí rộn ràng, kết bài vui vẻ',
  '- Có thể dùng cấu trúc liệt kê (ví dụ: "Khỉ thì nhảy, voi thì đi, cú thì bay đêm...")',
  '- Kết thúc bằng một câu reo vui như "Cùng nhau vui hát trong rừng xanh!"',
  'Ngôn ngữ: Tiếng Việt',
  'Phong cách: Nhẹ nhàng, vui nhộn, phù hợp với trẻ mẫu giáo',
]],
['prompt', 'Dán vào ô Style of Music của Suno', ['Children\'s pop; cheerful and energetic; 110-130 BPM; uses digital xylophone, ukulele, soft drums, hand claps, gentle synths; clear, cheerful vocals sung slowly for young kids.']],
['steps', [
  'Dán câu lệnh lời vào ChatGPT, sửa lời cho đúng ý, sao chép lời.',
  'Vào **suno.com**, đăng nhập, bấm **Create**, bật chế độ **Custom** (Tùy chỉnh).',
  'Dán lời vào ô **Lyrics**, dán đoạn tiếng Anh vào ô **Style of Music**, đặt tên bài, bấm **Create**.',
  'Nghe thử các bản được tạo, chọn bản phát âm tiếng Việt rõ nhất, tải về.',
]],
['tip', 'Tiểu học và THCS dùng cùng cấu trúc để làm bài hát ghi nhớ kiến thức, ví dụ "các hành tinh trong Hệ Mặt Trời". Đổi Style thành "upbeat pop, 100 BPM" cho lứa tuổi lớn hơn.'],

['lesson', 'D6', 'Tạo bài đọc và bài tập nhận diện câu lệnh lỗi'],
['prompt', 'Câu lệnh gốc', [
  '#NGỮ CẢNH',
  'Bạn là giáo viên Tiếng Anh lớp 6. Bạn đang giao bài viết cho học sinh tiểu học với chủ đề mùa hè của em.',
  '#HƯỚNG DẪN',
  'Yêu cầu học sinh viết một đoạn văn tiếng Anh khoảng 50 từ, kể về mùa hè của bản thân. Nội dung có thể bao gồm thời tiết, hoạt động ngoài trời, sở thích, nơi em đi chơi hoặc người em gặp.',
  '#YÊU CẦU',
  'Độ dài khoảng 100 từ',
  'Ngôn ngữ đơn giản, phù hợp học sinh lớp 4-5',
  'Viết ở ngôi thứ nhất (I, my...)',
  'Có ít nhất 3 hoạt động mùa hè',
  'Câu văn rõ ràng, đúng ngữ pháp',
]],
['why', 'Thử tìm 2 chỗ "vênh" trong câu lệnh trên', 'Câu lệnh nói **lớp 6** ở #NGỮ CẢNH nhưng **lớp 4-5** ở #YÊU CẦU. Nói **50 từ** ở #HƯỚNG DẪN nhưng **100 từ** ở #YÊU CẦU. Khi thông tin mâu thuẫn, AI phải tự chọn một bên. Đây là bài tập tốt để thầy cô tập đọc lại câu lệnh trước khi gửi.'],
['prompt', 'Phiên bản đã thống nhất (dùng cho lớp 4-5)', [
  '#NGỮ CẢNH',
  'Bạn là giáo viên Tiếng Anh tiểu học. Bạn đang giao bài viết cho học sinh lớp 4-5 với chủ đề mùa hè của em.',
  '#HƯỚNG DẪN',
  'Viết một đoạn văn tiếng Anh mẫu kể về mùa hè của bản thân. Nội dung có thể bao gồm thời tiết, hoạt động ngoài trời, sở thích, nơi em đi chơi hoặc người em gặp.',
  '#YÊU CẦU',
  'Độ dài khoảng 80 từ',
  'Ngôn ngữ đơn giản, phù hợp học sinh lớp 4-5',
  'Viết ở ngôi thứ nhất (I, my...)',
  'Có ít nhất 3 hoạt động mùa hè',
  'Câu văn rõ ràng, đúng ngữ pháp',
]],

['lesson', 'D7', 'Chỉ định phong cách đọc (tạo giọng đọc)'],
['why', 'Vì sao phải tả giọng kỹ như vậy?', 'Công cụ đọc văn bản bằng AI (ví dụ Google AI Studio, mục tạo giọng nói) đọc theo đúng mô tả. Nói "**giọng nam trung niên, trầm, đượm buồn**" thì bài thơ mang không khí khác hẳn giọng đọc máy bình thường. Mô tả càng cụ thể từng đoạn, giọng đọc càng có cảm xúc.'],
['prompt', 'Câu lệnh gốc (dán vào phần hướng dẫn giọng đọc)', [
  'Hãy đọc bài thơ "Thu điếu" của Nguyễn Khuyến bằng giọng nam trung niên, nhẹ, trầm, trong và đượm buồn, mang âm hưởng của một người nho sĩ ẩn dật, yêu thiên nhiên, chan chứa nỗi niềm thời thế.',
  'Giọng đọc cần chậm rãi, nhẹ nhàng, có nhấn nhá ở cuối mỗi câu thơ, thể hiện sự sâu lắng, lặng lẽ và thanh tao. Ở những câu miêu tả cảnh thu, hãy đọc với giọng trầm tĩnh, thong dong, như đang thả hồn giữa không gian yên ả.',
  'Đến đoạn "Tựa gối, ôm cần lâu chẳng được / Cá đâu đớp động dưới chân bèo", hãy tăng nhẹ cảm xúc, gợi nỗi cô đơn pha chút hài hước, tự giễu: một nét đặc trưng trong thơ Nguyễn Khuyến.',
  'Hãy giữ toàn bài thơ trong một nhịp điệu khoan thai, đậm chất thu, có chiều sâu nội tâm của một người trí sĩ giữa thời buổi đổi thay.',
  'Đọc toàn bài thơ "Thu điếu" theo phong cách này.',
  '"Ao thu lạnh lẽo nước trong veo, / Một chiếc thuyền câu bé tẻo teo. / Sóng biếc theo làn hơi gợn tí, / Lá vàng trước gió sẽ đưa vèo. / Tầng mây lơ lửng trời xanh ngắt, / Ngõ trúc quanh co khách vắng teo. / Tựa gối, ôm cần lâu chẳng được, / Cá đâu đớp động dưới chân bèo."',
]],
['tip', 'Thu điếu là thơ **thất ngôn bát cú Đường luật** (mỗi câu 7 chữ, 8 câu), không phải lục bát. Vì vậy sách ghi "nhấn nhá ở cuối mỗi câu thơ" để AI không đọc theo nhịp lục bát.'],
['levels', {
  mn: 'Hãy đọc bài thơ "Đàn gà con" bằng giọng nữ trẻ, trong, vui tươi, chậm rãi, nhấn vào các từ "chíp chíp" để trẻ đọc theo.',
  th: 'Hãy đọc đoạn văn "Mưa rào" bằng giọng nữ, lúc đầu nhẹ nhàng, đến đoạn mưa to thì nhanh và mạnh hơn.',
  thcs: 'Dùng nguyên câu lệnh gốc với bài thơ đang học ở lớp mình.',
}],

['lesson', 'D8', 'Tạo đoạn hội thoại hai giọng'],
['prompt', 'Câu lệnh gốc: nhờ ChatGPT viết kịch bản', [
  'Bạn hãy giúp tôi tạo một đoạn hội thoại bằng tiếng Việt giữa hai nhân vật, dùng trong Gemini Studio.',
  'Yêu cầu định dạng:',
  'Mở đầu bằng phần mô tả phong cách đọc:',
  '- Speaker 1 là hiệu trưởng, giọng điềm tĩnh, khích lệ.',
  '- Speaker 2 là học sinh, giọng vui vẻ nhưng hơi rụt rè.',
  'Sau mỗi lượt thoại, tạo nhịp ngắt giữa hai nhân vật bằng một dòng trống, để giúp đoạn hội thoại tự nhiên, chậm rãi hơn khi đọc.',
  'Viết đoạn hội thoại ngắn (khoảng 6-8 lượt trao đổi), sử dụng đúng định dạng:',
  'Speaker 1: [nội dung]',
  '(dòng trống)',
  'Speaker 2: [nội dung]',
  '(dòng trống)',
  '...',
  'Chủ đề: Một buổi phỏng vấn học bổng, nơi thầy/cô hiệu trưởng đặt câu hỏi thân thiện và học sinh trả lời một cách chân thành, lễ phép.',
  'Ngôn ngữ: Tiếng Việt, phù hợp với học sinh trung học cơ sở (THCS).',
  'Lưu ý: Ghi rõ "Speaker 1" và "Speaker 2" ở mỗi lượt nói.',
]],
['why', 'Vì sao phải ghi "Speaker 1", "Speaker 2"?', 'Công cụ tạo giọng nhiều người đọc (Google AI Studio) nhận diện ai đang nói nhờ đúng hai nhãn này. Mỗi nhãn được gán một giọng riêng. Sai nhãn là máy đọc lẫn giọng.'],
['steps', [
  'Gửi câu lệnh trên cho ChatGPT hoặc Gemini để có kịch bản.',
  'Vào **aistudio.google.com**, chọn mục tạo giọng nói (Generate speech), chọn chế độ **nhiều người nói**.',
  'Dán kịch bản. Ở phần cài đặt giọng, chọn một giọng cho Speaker 1 và một giọng khác cho Speaker 2.',
  'Bấm **Run**, nghe thử, bấm biểu tượng tải về để lấy tệp âm thanh.',
]],
['prompt', 'Hội thoại nâng cao: cho AI đóng vai chuyên gia trò chuyện với học sinh', [
  'Hãy đóng vai: Một chuyên gia thân thiện về năng lượng bền vững, có khả năng giải thích dễ hiểu, đưa ra ví dụ thực tế và khuyến khích học sinh phát triển ý tưởng sáng tạo. Hãy thực hành một cuộc trò chuyện với một học sinh cấp 3 đang chuẩn bị cho một dự án nhỏ về "năng lượng bền vững", để cùng brainstorm các ý tưởng phù hợp và dễ thực hiện.',
  'Mục tiêu của cuộc trò chuyện:',
  '- Học sinh đặt câu hỏi và thảo luận với chuyên gia để chọn được một ý tưởng phù hợp với học sinh cấp 3 (có thể làm trong vòng 1-2 tuần).',
  '- Chuyên gia cần giúp học sinh hiểu rõ mỗi ý tưởng: Nội dung chính; Tại sao phù hợp với học sinh; Cách thực hiện (mô hình, khảo sát, thuyết trình, v.v.)',
  'Yêu cầu đối với AI:',
  '- Đóng vai chuyên gia năng lượng bền vững thân thiện, dễ tiếp cận.',
  '- Trả lời rõ ràng, phù hợp với trình độ học sinh cấp 3, không dùng quá nhiều thuật ngữ kỹ thuật.',
  '- Giữ giọng điệu nhẹ nhàng, động viên học sinh phát triển ý tưởng.',
  '- Trò chuyện qua lại như thật trong 1-2 phút (3-5 lượt trao đổi).',
  '- Cuối buổi, đưa ra phản hồi tích cực về tiềm năng của ý tưởng học sinh chọn.',
  'Ví dụ: "Mình thấy ý tưởng khảo sát về ý thức tiết kiệm điện trong lớp học là một hướng đi rất thực tế và dễ triển khai."',
]],
['tip', 'Thầy cô THCS đổi "học sinh cấp 3" thành "học sinh lớp 8" và thời gian dự án thành "1 tuần". Có thể bật chế độ trò chuyện bằng giọng nói trên điện thoại để học sinh nói chuyện trực tiếp với "chuyên gia".'],

// ===================== PHẦN E =====================
['pb'],
['part', 'PHẦN E', 'Buổi 4 · Deep Research và trợ lý chatbot', 'Giao AI đọc hàng chục nguồn thay mình và tạo trợ giảng ảo trả lời học sinh 24 giờ.'],

['lesson', 'E1', 'Deep Research: báo cáo chuyên sâu phục vụ giảng dạy'],
['why', 'Deep Research khác trò chuyện thường ở đâu?', '**Deep Research** (Nghiên cứu sâu) là chế độ AI tự lập kế hoạch, tự tìm và đọc nhiều trang web, rồi viết báo cáo dài có danh sách nguồn. Mỗi lần chạy mất vài phút. Có trong ChatGPT và Gemini: bấm dấu **+** hoặc mục **Công cụ** trong ô nhập, chọn **Deep Research**.'],
['img', 'h13-deep-research', 'Hình E1. Quy trình 4 bước khi dùng Deep Research.'],
['prompt', 'Câu lệnh gốc: chủ đề Nước sạch và vệ sinh (Khoa học 4)', [
  'Hãy lập một báo cáo chuyên sâu phục vụ giảng dạy chủ đề "Nước sạch và vệ sinh" trong chương trình Khoa học lớp 4, bao gồm:',
  '- Tổng quan kiến thức về nước sạch và tầm quan trọng đối với sức khỏe học sinh tiểu học',
  '- Thực trạng tiếp cận nước sạch và điều kiện vệ sinh tại một số tỉnh/thành Việt Nam (tỷ lệ hộ dân có nước máy, nhà vệ sinh hợp vệ sinh...)',
  '- Ảnh hưởng của việc thiếu nước sạch đến sức khỏe học sinh (các bệnh phổ biến, khả năng đến trường)',
  '- Gợi ý hoạt động học tập và giải pháp thực hành tại lớp học, gia đình và cộng đồng',
  'Yêu cầu:',
  '- Dựa trên tài liệu hướng dẫn của UNICEF về WASH trong trường học (link: https://www.unicef.org/kyrgyzstan/media/1586/file/WASH%20Guidebook-Eng_0.pdf%20.pdf)',
  '- Bổ sung thông tin mới nhất (2023-2025) từ các nguồn đáng tin cậy như Bộ Y tế, Tổng cục Thống kê, UNICEF Việt Nam, báo chính thống (VnExpress, Tuổi Trẻ...), World Bank...',
]],
['p', '**WASH** là viết tắt tiếng Anh của Nước, Vệ sinh môi trường và Vệ sinh cá nhân. Câu lệnh chỉ rõ **nguồn gốc** (tài liệu UNICEF) và **mốc thời gian** (2023-2025) nên báo cáo bám sát thực tế.'],

['lesson', 'E2', 'Deep Research để kiểm chứng thông tin'],
['p', 'Cách làm: dán một đoạn văn bản (ví dụ một đoạn trong báo cáo ở E1, hoặc một tin trên mạng) rồi yêu cầu AI kiểm tra từng số liệu với nguồn gốc.'],
['prompt', 'Câu lệnh mẫu kiểm chứng', ['Hãy kiểm tra độ chính xác của từng số liệu và từng nhận định trong đoạn văn dưới đây. Với mỗi ý, cho biết: đúng, sai hay chưa đủ căn cứ, kèm đường link nguồn gốc. Trình bày dạng bảng.', '[dán đoạn văn cần kiểm tra]']],
['tip', 'Ngay cả khi AI đưa link, thầy cô vẫn mở link đó và tìm đúng con số trên trang. Nếu không tìm thấy, coi như số liệu chưa được xác minh.'],

['lesson', 'E3', 'Deep Research trong đời sống và nghiên cứu'],
['prompt', 'Câu lệnh gốc: lên lịch trình du lịch', ['Lịch trình cụ thể bao gồm địa điểm đẹp, tất cả chi phí ăn ở, vé máy bay tới Đà Lạt khởi hành từ thành phố Hồ Chí Minh từ ngày 31/08 tới 4/09? Đoàn bao gồm 2 người lớn và một bé trai yêu động vật 5 tuổi.']],
['p', 'Chi tiết "**bé trai yêu động vật 5 tuổi**" khiến AI ưu tiên điểm đến có vườn thú, nông trại. Đây là ví dụ về việc một chi tiết nhỏ thay đổi cả kết quả. Sau khi có báo cáo, có thể yêu cầu thêm: "Tạo infographic từ báo cáo này".'],
['prompt', 'Câu lệnh gốc: nghiên cứu khoa học', ['Đưa ba câu hỏi nghiên cứu (research questions) tiềm năng tập trung khám phá mối quan hệ giữa công cụ hỗ trợ AI và độ chính xác chẩn đoán trong X quang, chỉ rõ phương thức (ví dụ: MRI, CT) dựa vào nguồn từ các tạp chí khoa học uy tín!']],
['tip', 'Giáo viên làm sáng kiến kinh nghiệm hoặc nghiên cứu khoa học sư phạm ứng dụng: thay chủ đề X quang bằng đề tài của mình, ví dụ "mối quan hệ giữa trò chơi học tập và khả năng ghi nhớ từ vựng của học sinh lớp 3".'],

['lesson', 'E4', 'Xây dựng chatbot trợ giảng với Google Gemini'],
['why', 'System prompt là gì?', 'Là **bản hướng dẫn cố định** thầy cô viết một lần cho chatbot. Từ đó mọi học sinh hỏi đều được trả lời theo đúng quy tắc này. Trên Gemini, chatbot riêng gọi là **Gem**.'],
['img', 'h12-chatbot', 'Hình E4. Bốn bước tạo trợ giảng ảo.'],
['prompt', 'System prompt gốc: trợ giảng Vật lý 7', [
  'Bạn là một trợ giảng ảo chuyên hỗ trợ giáo viên và học sinh môn Vật lý lớp 7 tại Việt Nam.',
  'Nhiệm vụ chính của bạn là giúp học sinh ôn tập các kiến thức thuộc Chương 1 - Quang học, dựa trên nội dung trong tài liệu đính kèm có tên "Vatly7.pdf", trích từ sách giáo khoa Vật lý lớp 7 - chương trình phổ thông cơ bản hiện hành.',
  'Khi học sinh đặt câu hỏi, bạn cần:',
  '- Trả lời rõ ràng, chính xác, ngắn gọn, phù hợp với trình độ học sinh lớp 7',
  '- Giải thích khái niệm bằng ngôn ngữ đơn giản, có ví dụ thực tế minh họa nếu cần',
  '- Duy trì giọng điệu thân thiện, khích lệ, giúp học sinh hiểu và yêu thích môn học',
  'Khi học sinh hỏi đáp án trực tiếp các bài tập, không đưa ra ngay đáp án.',
  'Thay vào đó:',
  '- Hướng dẫn học sinh tư duy từng bước',
  '- Gợi ý phương pháp hoặc đặt câu hỏi gợi mở để học sinh tự tìm ra lời giải',
]],
['steps', [
  'Vào **gemini.google.com**, ở cột bên trái chọn **Khám phá Gem** (hoặc **Trình quản lý Gem**), bấm **Gem mới**.',
  'Ô **Tên**: gõ "Trợ giảng Vật lý 7". Ô **Hướng dẫn**: dán nguyên system prompt ở trên.',
  'Mục **Kiến thức**: bấm dấu **+** tải lên tệp Vatly7.pdf.',
  'Bấm **Lưu**. Tự đóng vai học sinh hỏi thử, ví dụ "Cho em đáp án bài 3" để xem chatbot có gợi mở thay vì đưa đáp án không.',
  'Ổn rồi thì bấm **Chia sẻ** để lấy link gửi học sinh.',
]],
['prompt', 'System prompt thứ hai: chuyên gia tạo câu hỏi trắc nghiệm', [
  'Bạn là chuyên gia xây dựng các câu hỏi trắc nghiệm. Câu hỏi trắc nghiệm được xây dựng từ nội dung người dùng cung cấp. Các mức độ câu hỏi gồm có Nhận biết, Thông hiểu, Vận dụng và Vận dụng cao. Các mức độ được hiểu như sau:',
  '- Mức Nhận biết: Nhắc lại được kiến thức, kĩ năng đã học.',
  '- Mức Thông hiểu: Trình bày, giải thích được kiến thức theo cách hiểu của cá nhân.',
  '- Mức Vận dụng: Biết vận dụng kiến thức, kĩ năng đã học để giải quyết những vấn đề quen thuộc, tương tự trong học tập, cuộc sống.',
  '- Mức Vận dụng cao: Vận dụng các kiến thức, kĩ năng đã học để giải quyết vấn đề mới hoặc đưa ra những phản hồi hợp lý trong học tập, cuộc sống một cách linh hoạt.',
]],
['tip', 'Gem thứ hai này là "máy ra đề" dùng chung cho mọi môn. Mỗi lần dùng, thầy cô chỉ cần dán nội dung bài học và gõ "Tạo 10 câu: 4 nhận biết, 3 thông hiểu, 2 vận dụng, 1 vận dụng cao".'],

['lesson', 'E5', 'Xây dựng chatbot với Poe'],
['prompt', 'System prompt gốc: trợ giảng Hóa học 10', [
  'Bạn là một trợ giảng cho môn Hóa học với nhiều năm kinh nghiệm giảng dạy, chuyên môn vững chắc.',
  'Bạn đang giảng dạy môn Hóa học lớp 10. Bạn có thể trả lời thắc mắc của học sinh trong chương trình Hóa học lớp 10, bộ sách Kết nối tri thức với cuộc sống trong file đính kèm.',
  'Chỉ trả lời các câu hỏi về môn hóa, đặc biệt là lớp 10 theo nội dung sách, không trả lời các câu hỏi khác.',
  'Khi học sinh hỏi bài tập thì đưa ra hướng dẫn và giải thích rõ ràng, dễ hiểu, mang tính gợi ý gợi mở cho học sinh, không đưa đáp án ngay từ đầu.',
]],
['p', 'Câu "**Chỉ trả lời các câu hỏi về môn hóa... không trả lời các câu hỏi khác**" là hàng rào: học sinh hỏi chuyện ngoài lề, chatbot từ chối. Trên **poe.com**: đăng nhập, bấm **Create bot** (Tạo bot), đặt tên, dán system prompt vào ô hướng dẫn, tải tệp SGK vào mục cơ sở kiến thức, bấm tạo.'],
['levels', {
  mn: 'Tạo chatbot "Góc phụ huynh": trả lời phụ huynh về thực đơn, lịch học, cách chuẩn bị đồ cho bé, dựa trên tệp thông báo của lớp. Không trả lời câu hỏi về sức khỏe riêng của từng trẻ.',
  th: 'Tạo chatbot "Bạn học Toán lớp 3": chỉ trả lời về Toán lớp 3, không đưa đáp án ngay, dùng câu ngắn và ví dụ về trái cây, đồ chơi.',
  thcs: 'Dùng nguyên khung, đổi thành môn và lớp đang dạy.',
}],

['lesson', 'E6', 'Magic School: chatbot dựng sẵn cho giáo viên'],
['why', 'Magic School là gì?', '**Magic School** (magicschool.ai) là bộ công cụ AI làm riêng cho giáo viên: lên kế hoạch bài học, tạo đề trắc nghiệm, làm rubric và tạo chatbot cho học sinh. Thầy cô chọn công cụ, điền vào các ô có sẵn, không cần tự viết câu lệnh dài.'],
['prompt', 'Công cụ Lên kế hoạch bài học', ['Lên kế hoạch bài học cho Bài 4 - Sự hình thành trái đất, vỏ Trái Đất và vật liệu cấu tạo vỏ trái đất, bao gồm kế hoạch bài học chi tiết cho tiết học 45 phút, mục tiêu kiến thức kỹ năng, chi tiết các hoạt động... Trình bày bằng tiếng Việt']],
['tip', 'Công cụ Magic School mặc định trả lời tiếng Anh. Luôn thêm câu "**Trình bày bằng tiếng Việt**" ở cuối.'],
['p', '**Công cụ tạo đề trắc nghiệm:** chọn công cụ tạo câu hỏi trắc nghiệm, tải lên tệp SGK Tin học 6 (link ở Phụ lục), chọn số câu, gõ "Trình bày bằng tiếng Việt", bấm tạo.'],
['prompt', 'Xây dựng ngân hàng câu hỏi', ['Bạn là Hiệu trưởng của một trường trung học phổ thông ở Việt Nam. Bạn được mời làm Ban giám khảo một chương trình học bổng. Bạn sẽ đưa ra ít nhất 30 câu hỏi cho các bạn học sinh THCS để tìm ra được những học sinh năng lực học thuật và sự sáng tạo tốt nhất.']],
['prompt', 'System prompt cho chatbot phỏng vấn trên Magic School', [
  'Bạn là Hiệu trưởng của một trường trung học phổ thông ở Việt Nam. Bạn được mời làm Ban giám khảo một chương trình học bổng.',
  'Bạn đang phỏng vấn một học sinh trung học để tìm hiểu về năng lực học thuật, khả năng sáng tạo và giải quyết vấn đề.',
  'Mỗi lần chỉ đặt một câu hỏi và tham gia vào cuộc trò chuyện với học sinh.',
]],
['why', 'Vì sao "Mỗi lần chỉ đặt một câu hỏi"?', 'Thiếu câu này, AI sẽ tuôn ra cả 30 câu hỏi cùng lúc. Có câu này, cuộc trò chuyện diễn ra từng lượt giống phỏng vấn thật. Học sinh luyện được phản xạ trả lời.'],

// ===================== PHẦN F =====================
['pb'],
['part', 'PHẦN F', 'Dùng AI hiệu quả và có trách nhiệm', 'Những điều cần nhớ để AI giúp mình mà không gây hại cho học sinh.'],
['lesson', 'F1', 'Khung năng lực AI cho giáo viên của UNESCO'],
['p', 'UNESCO đưa ra khung năng lực AI cho giáo viên gồm **5 lĩnh vực**, mỗi lĩnh vực đi qua **3 cấp độ**: Tiếp thu (biết dùng), Đào sâu (dùng thành thạo vào dạy học), Sáng tạo (tự thiết kế cách dùng mới). Cuốn sách này đưa thầy cô đi hết cấp độ Tiếp thu và bước vào cấp độ Đào sâu.'],
['img', 'h14-unesco', 'Hình F1. Năm lĩnh vực năng lực AI của giáo viên.'],
['p', 'Ở Việt Nam, Quyết định 3439/QĐ-BGDĐT (15/12/2025) cũng xây dựng nội dung giáo dục AI cho học sinh phổ thông theo 4 mạch, trong đó có **tư duy lấy con người làm trung tâm** và **đạo đức AI**. Luật Trí tuệ nhân tạo 2025 khẳng định AI là công cụ hỗ trợ, con người quyết định cuối cùng. Vì vậy mọi bài trong sách đều kết thúc bằng bước **Kiểm** của giáo viên.'],
['bullets', [
  '**Tư duy lấy con người làm trung tâm:** AI hỗ trợ, con người quyết định. Thầy cô chịu trách nhiệm cuối cùng với mọi nội dung đưa vào lớp.',
  '**Đạo đức AI:** tôn trọng quyền riêng tư, bản quyền, công bằng giữa các học sinh.',
  '**Nền tảng và ứng dụng AI:** hiểu AI làm được gì, không làm được gì, chọn đúng công cụ.',
  '**Sư phạm AI:** đưa AI vào hoạt động dạy học sao cho học sinh vẫn phải tư duy.',
  '**AI cho phát triển nghề nghiệp:** dùng AI để tự học, nghiên cứu, chia sẻ với đồng nghiệp.',
]],
['lesson', 'F2', 'Ba màu đèn trước khi dán thông tin vào AI'],
['img', 'h15-an-toan', 'Hình F2. Phân loại thông tin theo 3 màu đèn.'],
['lesson', 'F3', 'Danh sách tự kiểm trước khi dùng sản phẩm của AI'],
['checklist', [
  'Kiến thức đúng với sách giáo khoa và chương trình đang dạy.',
  'Số liệu, trích dẫn, đường link đã được tự tay mở ra kiểm tra.',
  'Ngôn ngữ phù hợp lứa tuổi, không có từ ngữ vùng miền gây hiểu lầm.',
  'Ảnh, nhạc, video không có chi tiết sai lệch (lá cờ, trang phục, địa danh).',
  'Không có thông tin cá nhân của học sinh hay phụ huynh.',
  'Đề kiểm tra: mỗi câu trắc nghiệm có đúng 1 đáp án đúng, không trùng câu.',
  'Chatbot cho học sinh: đã tự thử hỏi 5 câu, kể cả câu "xin đáp án" và câu ngoài lề.',
  'Ảnh, giọng đọc, video do AI tạo ra đã có ghi chú nhận biết, ví dụ "Hình ảnh tạo bởi AI" (Luật Trí tuệ nhân tạo 2025).',
  'Tài liệu dùng làm nguồn (SGK, bài báo) đã ghi tên tác giả và nguồn gốc (Luật Sở hữu trí tuệ, Điều 25).',
  'Nếu dùng AI hỗ trợ soạn, thầy cô sẵn sàng giải thích với đồng nghiệp, phụ huynh cách mình đã dùng.',
]],

// ===================== PHỤ LỤC =====================
['pb'],
['part', 'PHỤ LỤC', 'Tra nhanh và mẫu điền sẵn', 'Mở phần này khi cần làm ngay, không cần đọc lại cả sách.'],
['lesson', 'P1', 'Bắt đầu theo cấp học'],
['img', 'h16-cap-hoc', 'Hình P1. Ba việc làm được ngay cho mỗi cấp học.'],
['table', ['Tôi muốn...', 'Mở bài', 'Công cụ'], [
  ['Có ý tưởng bài dạy thật nhanh', 'B1, B4', 'ChatGPT, Gemini'],
  ['Soạn bài giảng có slide, Quiz', 'B6', 'ChatGPT, Gemini'],
  ['Soạn giáo án góc trạm, STEM', 'C1, C2', 'ChatGPT, Gemini'],
  ['Ra đề tự luận, trắc nghiệm', 'C3 đến C6', 'ChatGPT, Gemini, Magic School'],
  ['Làm bảng tiêu chí chấm', 'C7', 'ChatGPT, Magic School'],
  ['Tạo ảnh minh họa', 'D1, D2', 'ChatGPT, Gemini, Canva'],
  ['Tạo trò chơi học tập', 'D3', 'Canva, Gemini (Canvas)'],
  ['Làm truyện tranh', 'D4', 'Google AI Studio, ChatGPT'],
  ['Sáng tác bài hát', 'D5', 'ChatGPT + Suno'],
  ['Tạo giọng đọc, hội thoại', 'D7, D8', 'Google AI Studio'],
  ['Tìm tài liệu, số liệu có nguồn', 'C9, E1, E2', 'NotebookLM, Deep Research'],
  ['Tạo trợ giảng cho học sinh', 'E4, E5, E6', 'Gemini (Gem), Poe, Magic School'],
]],
['lesson', 'P2', 'Mẫu câu lệnh đa năng: điền vào [ ] là dùng được'],
['prompt', 'Mẫu 6 mảnh ghép', ['Bạn là [vai trò, ví dụ: giáo viên Toán lớp 3 giàu kinh nghiệm]. Hãy [nhiệm vụ] cho [đối tượng: học sinh lớp mấy, trình độ thế nào] để [mục đích]. Trình bày [định dạng: bảng, gạch đầu dòng, số từ]. Giọng điệu [thân thiện, vui tươi, trang trọng].']],
['prompt', 'Mẫu 4 ngăn cho đề kiểm tra', ['#NGỮ CẢNH', 'Bạn là giáo viên [môn] lớp [...], bộ sách [...].', '#HƯỚNG DẪN', 'Đọc tài liệu ở mục ##Nội dung bài học. Dựa vào mục ##Mức độ nhận thức để phân loại câu hỏi.', '#DỮ LIỆU', '##Nội dung bài học: [tên tệp đính kèm]', '##Mức độ nhận thức: [dán định nghĩa 4 mức độ ở bài C6]', '#YÊU CẦU', '[số] câu trắc nghiệm 4 đáp án, chỉ có 1 đáp án đúng: [số] nhận biết, [số] thông hiểu, [số] vận dụng. Chỉ dùng nội dung trong tài liệu đính kèm. Có đáp án ở cuối.']],
['prompt', 'Mẫu system prompt cho chatbot', ['Bạn là trợ giảng môn [môn] lớp [...]. Chỉ trả lời câu hỏi về [phạm vi] dựa trên tài liệu đính kèm, không trả lời các câu hỏi khác. Trả lời ngắn gọn, thân thiện, phù hợp học sinh lớp [...]. Khi học sinh hỏi đáp án bài tập, không đưa ra ngay đáp án mà hướng dẫn từng bước và đặt câu hỏi gợi mở.']],
['lesson', 'P3', 'Câu nói thêm khi kết quả chưa ưng'],
['table', ['Kết quả bị...', 'Gõ tiếp câu này'], [
  ['Quá dài', 'Rút gọn còn một nửa, giữ ý chính.'],
  ['Quá khó với học sinh', 'Viết lại cho học sinh lớp [...] hiểu, câu ngắn, có ví dụ gần gũi.'],
  ['Chung chung', 'Cụ thể hơn: thêm ví dụ thực tế ở Việt Nam cho mỗi ý.'],
  ['Sai định dạng', 'Trình bày lại dạng bảng gồm các cột [...].'],
  ['Trả lời bằng tiếng Anh', 'Trình bày bằng tiếng Việt.'],
  ['Dừng giữa chừng', 'Viết tiếp.'],
  ['Nghi có số liệu sai', 'Cho biết nguồn của số liệu [...] kèm đường link.'],
]],
['lesson', 'P4', 'Liên kết tài liệu thực hành'],
['links', [
  ['Sách Family and Friends 4 - Class Book (bài C4)', 'https://drive.google.com/file/d/11eaMmXCfX1xJYn6odem3HItJUnz-AcPr/view?usp=sharing'],
  ['Tài liệu bài C4 (link rút gọn)', 'https://tinyurl.com/WS2Muc3'],
  ['Tài liệu Hóa học 10: đề bài và mô tả mức độ (bài C5)', 'https://tinyurl.com/WS2Muc4'],
  ['Tài liệu Tin học 6: ma trận, đặc tả, nội dung (bài C6)', 'https://tinyurl.com/WS2Muc6'],
  ['Ví dụ tìm kiếm và phân tích thông tin (bài C9)', 'https://tinyurl.com/WS2Notebook'],
  ['Hướng dẫn thực hành buổi 2, 3, 4', 'https://tinyurl.com/HdThucHanhWS2 · https://tinyurl.com/HdThucHanhWS3 · https://tinyurl.com/HdThucHanhWS4'],
  ['Canva cho giáo dục (bài D2, D3)', 'https://www.canva.com/vi_vn/giao-duc/'],
  ['Game tham khảo tạo bằng Canva (bài D3)', 'https://vnfeai.my.canva.site/gamehoctap01'],
  ['Game tham khảo tạo bằng Gemini (bài D3)', 'https://g.co/gemini/share/fcae4882cf2b'],
  ['Ví dụ báo cáo Deep Research: Nước sạch và vệ sinh (bài E1)', 'https://gemini.google.com/share/e0324042549d'],
  ['Ví dụ kiểm chứng thông tin (bài E2)', 'https://chatgpt.com/share/687f4092-96f4-8003-8931-c002ac35bae7'],
  ['Ví dụ báo cáo và infographic du lịch Đà Lạt (bài E3)', 'https://g.co/gemini/share/055dcd49d387 · https://g.co/gemini/share/9164e4f3c7e8'],
  ['Kết quả mẫu nghiên cứu khoa học (bài E3)', 'https://shorturl.at/nmkUM'],
  ['Tài liệu Vatly7.pdf (bài E4)', 'https://drive.google.com/file/d/1wrPa7W24GQVXR1RiknUdS08hrBtlr8TV/view?usp=sharing'],
  ['Sách giáo khoa Hóa 10 (bài E5)', 'https://drive.google.com/file/d/1Df3WKjQnYCWkISzsc9-S3TNHzEg0qtOK/view'],
  ['Chương trình GDPT 2018 môn Địa lý (bài E6)', 'https://drive.google.com/file/d/1Izea6mBXBOhRyw3cVdrmoNgpOwcbX8jZ/view?usp=sharing'],
  ['SGK Tin học 6 (bài E6)', 'https://drive.google.com/file/d/10w1g-hKK3_qelt_Kck0CZtxub6IVtUCH/view?usp=sharing'],
]],
];
