module.exports = [
['cover2', 'HƯỚNG DẪN TRƯỚC KHI SỬ DỤNG', 'Chuẩn bị, thiết lập an toàn, lộ trình 7 ngày và cách xử lý sự cố'],

['part', 'MỤC 1', 'Bộ tài liệu gồm những gì', 'Đọc mục này trước để biết mở tệp nào, khi nào.'],
['table', ['Tệp', 'Dùng để làm gì'], [
  ['01 · Sách Dạy cùng AI (Word, PDF)', 'Học từng bài. Mỗi bài có câu lệnh, lý do dùng câu chữ đó và phiên bản cho 3 cấp học.'],
  ['02 · Slide giới thiệu (PowerPoint)', 'Trình chiếu khi tập huấn, sinh hoạt tổ chuyên môn. Ít chữ, có ghi chú cho người nói.'],
  ['03 · Hướng dẫn trước khi sử dụng', 'Chính là tài liệu này: chuẩn bị tài khoản, thiết lập an toàn, lộ trình tự học.'],
  ['04 · Thư viện câu lệnh (Word)', 'Chỉ chứa câu lệnh để sao chép nhanh, xếp theo mã bài giống trong sách.'],
  ['05 · Thẻ tra nhanh 1 trang (PDF)', 'In ra dán cạnh máy tính. Có 6 mảnh ghép, 4 ngăn, 3 màu đèn, câu nói thêm.'],
]],
['p', '**Thứ tự khuyên dùng:** đọc tài liệu này (15 phút) → làm Phần A trong sách (20 phút) → mỗi ngày làm 1 phần theo lộ trình ở Mục 4 → giữ Thư viện câu lệnh và Thẻ tra nhanh để dùng lâu dài.'],

['part', 'MỤC 2', 'Chuẩn bị thiết bị và tài khoản', 'Làm một lần, khoảng 20 phút.'],
['lesson', '2.1', 'Thiết bị'],
['bullets', [
  '**Máy tính** (khuyên dùng) hoặc điện thoại có kết nối Internet ổn định. Máy tính giúp sao chép câu lệnh dài và tải tệp dễ hơn.',
  '**Trình duyệt Chrome** bản mới. Các công cụ trong sách đều chạy trên trình duyệt, không cần cài phần mềm.',
  '**Một tài khoản Gmail**. Hầu hết công cụ cho đăng nhập bằng Google. Khuyên dùng một Gmail riêng cho công việc.',
]],
['lesson', '2.2', 'Các công cụ dùng trong sách'],
['table', ['Công cụ · địa chỉ', 'Dùng ở bài', 'Ghi chú'], [
  ['ChatGPT · chatgpt.com', 'Hầu hết các bài', 'Có bản miễn phí. Tạo ảnh, Deep Research có thể bị giới hạn lượt dùng.'],
  ['Gemini · gemini.google.com', 'B, C, D3, E1, E4', 'Có bản miễn phí. Gem (chatbot riêng) và Canvas (trò chơi) nằm trong Gemini.'],
  ['NotebookLM · notebooklm.google.com', 'C9', 'Hỏi đáp dựa trên tài liệu thầy cô tải lên.'],
  ['Google AI Studio · aistudio.google.com', 'D4, D7, D8', 'Tạo giọng đọc, hội thoại nhiều giọng, truyện tranh.'],
  ['Canva · canva.com', 'D2, D3', 'Sửa ảnh, tạo trò chơi bằng câu lệnh. Giáo viên có thể đăng ký Canva cho Giáo dục.'],
  ['Suno · suno.com', 'D5', 'Tạo bài hát từ lời và mô tả phong cách.'],
  ['Overleaf · overleaf.com', 'C8', 'Dán mã LaTeX để xuất đề có công thức toán ra PDF.'],
  ['Poe · poe.com', 'E5', 'Tạo chatbot riêng.'],
  ['Magic School · magicschool.ai', 'E6', 'Bộ công cụ AI cho giáo viên. Nên thêm câu "Trình bày bằng tiếng Việt".'],
]],
['tip', 'Giới hạn miễn phí, tên gói và tên nút của các công cụ thay đổi khá thường xuyên. Nếu không thấy nút giống trong sách, hãy tìm theo **chức năng** (ví dụ biểu tượng dấu + để đính kèm tệp) thay vì tìm đúng tên.'],
['lesson', '2.3', 'Không nên cài hay mua gì trước'],
['p', 'Học hết Phần A và Phần B chỉ cần bản miễn phí của ChatGPT hoặc Gemini. Chỉ cân nhắc gói trả phí khi thầy cô thấy mình dùng hằng ngày và thường xuyên hết lượt. Cẩn thận với các ứng dụng giả mạo trên kho ứng dụng điện thoại: chỉ tải ứng dụng có tên nhà phát triển là OpenAI (ChatGPT) hoặc Google (Gemini).'],

['part', 'MỤC 3', 'Thiết lập an toàn ngay từ đầu', 'Làm trước khi dán bất kỳ tài liệu nào của trường vào AI.'],
['lesson', '3.1', 'Hạn chế dùng cuộc trò chuyện của mình để huấn luyện AI'],
['steps', [
  '**ChatGPT:** bấm vào ảnh đại diện → **Cài đặt** (Settings) → **Kiểm soát dữ liệu** (Data controls) → tắt mục **Cải thiện mô hình cho mọi người**.',
  '**Gemini:** bấm **Cài đặt và trợ giúp** → **Hoạt động** → xem và chọn tắt lưu hoạt động nếu thầy cô không muốn lưu.',
  'Tên mục có thể khác một chút giữa các phiên bản. Gõ vào ô hỏi của chính công cụ: "Làm sao tắt việc dùng dữ liệu trò chuyện của tôi để huấn luyện?" để được chỉ đường mới nhất.',
]],
['lesson', '3.2', 'Quy tắc 3 màu đèn'],
['img', 'h15-an-toan', 'Phân loại thông tin trước khi dán vào AI.'],
['lesson', '3.3', 'Học sinh có được tự dùng AI không?'],
['bullets', [
  'Nhiều công cụ AI quy định **độ tuổi tối thiểu** trong điều khoản sử dụng (thường là 13 tuổi, dưới 18 tuổi cần phụ huynh đồng ý). Thầy cô kiểm tra điều khoản của từng công cụ trước khi cho học sinh dùng trực tiếp.',
  'Với **mầm non và tiểu học**: giáo viên dùng AI để soạn học liệu. Trẻ chỉ tiếp xúc với **sản phẩm cuối** (ảnh, bài hát, trò chơi) đã được giáo viên kiểm tra.',
  'Với **THCS**: nếu cho học sinh dùng chatbot (bài E4, E5), gửi thông báo cho phụ huynh, nói rõ chatbot dùng để làm gì và không đưa đáp án ngay.',
  'Dữ liệu cá nhân của học sinh được bảo vệ theo **Luật Bảo vệ dữ liệu cá nhân số 91/2025/QH15** (hiệu lực từ 01/1/2026). Không dán họ tên, ảnh, điểm số, thông tin sức khỏe của học sinh vào công cụ AI.',
  'Khi hướng dẫn học sinh dùng AI, bám theo **Khung năng lực số cho người học** (Thông tư 02/2025/TT-BGDĐT): dùng an toàn, có trách nhiệm, trung thực.',
  'Tuân thủ quy định của nhà trường và cơ quan quản lý giáo dục về sử dụng công nghệ.',
]],
['lesson', '3.4', 'Minh bạch khi dùng AI'],
['p', '**Luật Trí tuệ nhân tạo số 134/2025/QH15** (hiệu lực từ 01/3/2026) yêu cầu nội dung do AI tạo ra có dấu hiệu nhận biết phù hợp. Khi học liệu có phần do AI hỗ trợ tạo ra (ảnh, bài hát, giọng đọc), hãy ghi chú nhỏ "Có sử dụng AI hỗ trợ". Điều này giúp học sinh hiểu cách dùng AI đúng đắn và tránh hiểu lầm với đồng nghiệp, phụ huynh.'],

['part', 'MỤC 4', 'Lộ trình tự học 7 ngày', 'Mỗi ngày khoảng 30 phút. Mỗi ngày kết thúc bằng một sản phẩm dùng được ngay cho lớp mình.'],
['table', ['Ngày', 'Học phần', 'Sản phẩm cuối ngày'], [
  ['1', 'Phần A (A1 đến A3)', 'Chạy được câu lệnh đầu tiên, tách được 6 mảnh ghép của câu lệnh mẫu.'],
  ['2', 'Phần B (B1 đến B5)', 'Một đoạn dẫn nhập bài học theo kỹ thuật kết hợp nhiều yếu tố.'],
  ['3', 'Phần B (B6, B7) và C1, C2', 'Một giáo án góc trạm hoặc STEM cho bài dạy tuần tới.'],
  ['4', 'Phần C (C3 đến C7)', 'Một đề kiểm tra 10 câu có đáp án và một bảng tiêu chí chấm.'],
  ['5', 'Phần D (D1 đến D4)', 'Ba ảnh minh họa và một trò chơi học tập.'],
  ['6', 'Phần D (D5 đến D8)', 'Một bài hát hoặc một đoạn hội thoại hai giọng.'],
  ['7', 'Phần E và F', 'Một chatbot trợ giảng đã tự thử 5 câu hỏi. Tự chấm theo danh sách F3.'],
]],
['tip', 'Không cần làm đủ mọi bài. Giáo viên mầm non có thể bỏ C5, C6, C8. Giáo viên THCS có thể bỏ D5. Dùng bảng P1 trong sách để chọn bài theo việc cần làm.'],

['part', 'MỤC 5', '10 quy tắc vàng khi viết câu lệnh', 'Rút ra từ toàn bộ câu lệnh trong sách.'],
['checklist', [
  '**Giao vai** cho AI: "Bạn là giáo viên... nhiều năm kinh nghiệm".',
  '**Nói rõ đối tượng:** lớp mấy, bao nhiêu tuổi, trình độ ra sao.',
  '**Nói rõ mục đích:** để thuyết trình, để ôn thi, để chơi khởi động.',
  '**Dùng con số:** 10 slide, 5 câu, 7 phút, 300 từ, 2-3 câu mỗi ý.',
  '**Chỉ định cách trình bày:** bảng, gạch đầu dòng, theo cấu trúc 5 mục.',
  '**Câu lệnh dài thì chia 4 ngăn** #NGỮ CẢNH #HƯỚNG DẪN #DỮ LIỆU #YÊU CẦU.',
  '**Đặt tên tài liệu bằng ##** và viết tên đó giống hệt ở mọi chỗ.',
  '**Nói cả điều không được làm:** "không đưa ra ngay đáp án", "không có chữ trong ảnh".',
  '**Đọc lại trước khi gửi** để bắt lỗi mâu thuẫn (lớp 6 hay lớp 4, 50 từ hay 100 từ).',
  '**Chưa ưng thì nói tiếp**, không mở cuộc mới. Việc mới thì mở cuộc mới.',
]],

['part', 'MỤC 6', 'Xử lý sự cố thường gặp', 'Tra bảng này trước khi bỏ cuộc.'],
['table', ['Tình huống', 'Cách xử lý'], [
  ['Không đăng nhập được', 'Thử tab ẩn danh, hoặc đăng xuất Gmail khác đang mở. Kiểm tra mạng của trường có chặn trang đó không.'],
  ['AI trả lời bằng tiếng Anh', 'Gõ thêm "Trình bày bằng tiếng Việt". Magic School nên thêm câu này ngay trong câu lệnh.'],
  ['Câu trả lời bị cắt ngang', 'Gõ "Viết tiếp". Với đề dài, yêu cầu chia làm 2 lần, mỗi lần 20 câu.'],
  ['Tải tệp lên bị lỗi', 'Tệp PDF quá lớn hoặc là ảnh chụp. Tách tệp thành phần nhỏ, chỉ giữ các trang cần dùng.'],
  ['Ảnh có chữ sai dấu tiếng Việt', 'Yêu cầu "không có chữ trong ảnh", sau đó thêm chữ bằng PowerPoint hoặc Canva.'],
  ['Nhân vật trong truyện tranh mỗi cảnh một kiểu', 'Dùng câu lệnh gán mã số nhân vật ở bài D4. Nhắc lại mô tả nhân vật trong mỗi cảnh.'],
  ['Báo hết lượt dùng', 'Chờ theo thời gian công cụ báo, hoặc chuyển sang công cụ khác (ChatGPT sang Gemini và ngược lại).'],
  ['Link AI đưa ra không mở được', 'AI có thể bịa link. Tự tìm lại trên Google bằng tên bài viết. Không tìm thấy thì không dùng.'],
  ['Trò chơi tạo ra bị lỗi', 'Mô tả lỗi bằng lời thường: "Bấm nút Bắt đầu không có gì xảy ra, hãy sửa".'],
  ['Link trong Phụ lục P4 không mở được', 'Một số link là tài liệu của khóa tập huấn, có thể đã được chủ sở hữu thay đổi quyền truy cập. Dùng tài liệu SGK của chính lớp mình để thay.'],
]],

['part', 'MỤC 7', 'Nếu dùng bộ tài liệu để tập huấn cho đồng nghiệp', 'Gợi ý chia 4 buổi, khớp với 4 phần của sách và slide.'],
['table', ['Buổi', 'Nội dung', 'Hoạt động thực hành'], [
  ['1', 'Phần A, B · Slide 1 đến 10', 'Mỗi người chạy 4 kỹ thuật trên cùng một bài dạy của mình, rồi tự chấm câu lệnh theo 6 mảnh ghép.'],
  ['2', 'Phần C · Slide 11 đến 14', 'Theo tổ chuyên môn: làm 1 đề 10 câu theo 4 ngăn và 1 rubric. Đổi đề cho nhau để kiểm tra.'],
  ['3', 'Phần D · Slide 15 đến 17', 'Mỗi nhóm làm 1 bộ học liệu cho cùng một bài: ảnh, trò chơi, bài hát hoặc giọng đọc.'],
  ['4', 'Phần E, F · Slide 18 đến 24', 'Mỗi người tạo 1 chatbot, nhờ đồng nghiệp đóng vai học sinh "xin đáp án" để thử.'],
]],
['tip', 'Trước mỗi buổi: kiểm tra mạng phòng tập huấn mở được các trang ở Mục 2.2. Nhắc học viên mang máy tính và nhớ mật khẩu Gmail.'],
['pb'],
['basisTable'],
];
